/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PTE3 (number 27), RX
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_DEBUG_pte3_PORT PTE                 /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_pte3_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_pte3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTE14 (number 26), TX
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_DEBUG_pte14_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_pte14_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_pte14_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Debug(void);

/*! @name PTE16 (number 4), TP0
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITPINS_GPIO_TP0_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITPINS_GPIO_TP0_GPIO kSIUL2_PTE           /*!<@brief GPIO peripheral port */
#define BOARD_INITPINS_GPIO_TP0_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_TP0_GPIO_PIN_MASK (1U << 144U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_TP0_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_TP0_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_TP0_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PTE15 (number 5), TP1
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITPINS_GPIO_TP1_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITPINS_GPIO_TP1_GPIO kSIUL2_PTE           /*!<@brief GPIO peripheral port */
#define BOARD_INITPINS_GPIO_TP1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_TP1_GPIO_PIN_MASK (1U << 143U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_TP1_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_TP1_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_TP1_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PTC16 (number 66), LED1
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITPINS_GPIO_LED1_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITPINS_GPIO_LED1_GPIO kSIUL2_PTC           /*!<@brief GPIO peripheral port */
#define BOARD_INITPINS_GPIO_LED1_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_LED1_GPIO_PIN_MASK (1U << 80U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_LED1_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_LED1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_LED1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTC14 (number 71), LED3
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITPINS_GPIO_LED3_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITPINS_GPIO_LED3_GPIO kSIUL2_PTC           /*!<@brief GPIO peripheral port */
#define BOARD_INITPINS_GPIO_LED3_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_LED3_GPIO_PIN_MASK (1U << 78U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_LED3_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_LED3_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_LED3_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTB22 (number 67), LED2
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITPINS_GPIO_LED2_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITPINS_GPIO_LED2_GPIO kSIUL2_PTB           /*!<@brief GPIO peripheral port */
#define BOARD_INITPINS_GPIO_LED2_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_GPIO_LED2_GPIO_PIN_MASK (1U << 54U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_LED2_PORT PTB                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_LED2_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_LED2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTB23 (number 69), SW2
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITPINS_GPIO_SW2_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITPINS_GPIO_SW2_GPIO kSIUL2_PTB           /*!<@brief GPIO peripheral port */
#define BOARD_INITPINS_GPIO_SW2_GPIO_PIN_MASK (1U << 55U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_SW2_PORT PTB                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_SW2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_SW2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PTD5 (number 53), SW3
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_GPIO_SW3_PORT PTD                 /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_GPIO_SW3_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_GPIO_SW3_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief 
 *
 */
void BOARD_InitPins_GPIO(void);

/*! @name PTD1 (number 7), PWM_AT
  @{ */

/* Defined symbols */
#define BOARD_EMIOSPINS_PWM_AT_PORT PTD                 /*!<@brief PORT peripheral base pointer */
#define BOARD_EMIOSPINS_PWM_AT_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_EMIOSPINS_PWM_AT_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PTD0 (number 8), PWM_AB
  @{ */

/* Defined symbols */
#define BOARD_EMIOSPINS_PWM_AB_PORT PTD                 /*!<@brief PORT peripheral base pointer */
#define BOARD_EMIOSPINS_PWM_AB_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_EMIOSPINS_PWM_AB_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PTE11 (number 9), PWM_BT
  @{ */

/* Defined symbols */
#define BOARD_EMIOSPINS_PWM_BT_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_EMIOSPINS_PWM_BT_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_EMIOSPINS_PWM_BT_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PTB16 (number 112), PWM_BB
  @{ */

/* Defined symbols */
#define BOARD_EMIOSPINS_PWM_BB_PORT PTB                  /*!<@brief PORT peripheral base pointer */
#define BOARD_EMIOSPINS_PWM_BB_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_EMIOSPINS_PWM_BB_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PTB17 (number 110), PWM_CT
  @{ */

/* Defined symbols */
#define BOARD_EMIOSPINS_PWM_CT_PORT PTB                  /*!<@brief PORT peripheral base pointer */
#define BOARD_EMIOSPINS_PWM_CT_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_EMIOSPINS_PWM_CT_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PTA17 (number 109), PWM_CB
  @{ */

/* Defined symbols */
#define BOARD_EMIOSPINS_PWM_CB_PORT PTA                  /*!<@brief PORT peripheral base pointer */
#define BOARD_EMIOSPINS_PWM_CB_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_EMIOSPINS_PWM_CB_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_eMIOSPins(void);

/*! @name PTC23 (number 87), PWM_AT
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_LCU_ptc23_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCU_ptc23_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCU_ptc23_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTC24 (number 88), PWM_AB
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_LCU_ptc24_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCU_ptc24_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCU_ptc24_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTC25 (number 89), PWM_BT
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_LCU_ptc25_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCU_ptc25_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCU_ptc25_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTC26 (number 91), PWM_BB
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_LCU_ptc26_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCU_ptc26_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCU_ptc26_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTC27 (number 93), PWM_CT
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_LCU_ptc27_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCU_ptc27_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCU_ptc27_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PTC28 (number 96), PWM_CB
  @{ */

/* Defined symbols */
#define BOARD_INITPINS_LCU_ptc28_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LCU_ptc28_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LCU_ptc28_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_LCU(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_ADC(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_TRGIN(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
